from PySide6.QtWidgets import (QLabel, QLineEdit, QPushButton, QDateEdit, QSpinBox,
                               QGroupBox, QHBoxLayout, QVBoxLayout, QWidget, QListView)
from PySide6.QtGui import QFont


class SellForm(QGroupBox):
    def __init__(self):
        super().__init__()
        self.layout = QHBoxLayout()
        self.setLayout(self.layout)
        self.setFixedHeight(500)
        self.font_normal = QFont('Arial', 10)

        # ++++++++++++++++++++++++++ FORM LEFT SECTION +++++++++++++++++++
        left_section = QWidget()
        left_section_layout = QVBoxLayout()
        left_section.setLayout(left_section_layout)
        self.layout.addWidget(left_section)

        name_holder = QWidget()
        name_holder.setMaximumHeight(80)
        name_holder.setMaximumWidth(500)
        name_holder_layout = QVBoxLayout()
        name_holder.setLayout(name_holder_layout)
        left_section_layout.addWidget(name_holder)
        name_label = QLabel('Medicine Name')
        name_label.setFont(self.font_normal)
        name_holder_layout.addWidget(name_label)
        name_input = QLineEdit()
        name_input.setEnabled(False)
        name_input.setFont(self.font_normal)
        name_holder_layout.addWidget(name_input)

        description_holder = QWidget()
        description_holder.setMaximumHeight(80)
        description_holder.setMaximumWidth(500)
        description_holder_layout = QVBoxLayout()
        description_holder.setLayout(description_holder_layout)
        left_section_layout.addWidget(description_holder)
        description_label = QLabel('Description')
        description_label.setFont(self.font_normal)
        description_holder_layout.addWidget(description_label)
        description_input = QLineEdit()
        description_input.setEnabled(False)
        description_input.setFont(self.font_normal)
        description_holder_layout.addWidget(description_input)

        mfg_date_holder = QWidget()
        mfg_date_holder.setMaximumWidth(500)
        mfg_date_holder.setMaximumHeight(80)
        mfg_date_holder_layout = QVBoxLayout()
        mfg_date_holder.setLayout(mfg_date_holder_layout)
        left_section_layout.addWidget(mfg_date_holder)
        mfg_date_label = QLabel('Manufactured Date')
        mfg_date_label.setFont(self.font_normal)
        mfg_date_holder_layout.addWidget(mfg_date_label)
        mfg_date_input = QDateEdit()
        mfg_date_input.setEnabled(False)
        mfg_date_input.setFont(self.font_normal)
        mfg_date_holder_layout.addWidget(mfg_date_input)

        expiry_date_holder = QWidget()
        expiry_date_holder.setMaximumWidth(500)
        expiry_date_holder.setMaximumHeight(80)
        expiry_date_holder_layout = QVBoxLayout()
        expiry_date_holder.setLayout(expiry_date_holder_layout)
        left_section_layout.addWidget(expiry_date_holder)
        expiry_date_label = QLabel('Expiry Date')
        expiry_date_label.setFont(self.font_normal)
        expiry_date_holder_layout.addWidget(expiry_date_label)
        expiry_date_input = QDateEdit()
        expiry_date_input.setEnabled(False)
        expiry_date_input.setFont(self.font_normal)
        expiry_date_holder_layout.addWidget(expiry_date_input)

        # ++++++++++++++++++++++++++ FORM RIGHT SECTION +++++++++++++++++++
        right_section = QWidget()
        right_section_layout = QVBoxLayout()
        right_section.setLayout(right_section_layout)
        self.layout.addWidget(right_section)

        quantity_holder = QWidget()
        quantity_holder.setMaximumWidth(500)
        quantity_holder.setMaximumHeight(80)
        quantity_holder_layout = QVBoxLayout()
        quantity_holder.setLayout(quantity_holder_layout)
        quantity_label = QLabel('Choose Quantity')
        quantity_label.setFont(self.font_normal)
        quantity_holder_layout.addWidget(quantity_label)
        quantity_input = QSpinBox()
        quantity_input.setMinimum(0)
        quantity_input.setMaximum(1000)
        quantity_input.setFont(self.font_normal)
        quantity_holder_layout.addWidget(quantity_input)
        right_section_layout.addWidget(quantity_holder)

        price_holder = QWidget()
        price_holder.setMaximumWidth(500)
        price_holder.setMaximumHeight(80)
        price_holder_layout = QVBoxLayout()
        price_holder.setLayout(price_holder_layout)
        price_label = QLabel('Unit Price')
        price_label.setFont(self.font_normal)
        price_holder_layout.addWidget(price_label)
        price_input = QLineEdit('1000')
        price_input.setEnabled(False)
        price_input.setFont(self.font_normal)
        price_holder_layout.addWidget(price_input)
        right_section_layout.addWidget(price_holder)

        total_holder = QWidget()
        total_holder.setMaximumWidth(500)
        total_holder.setMaximumHeight(80)
        total_holder_layout = QVBoxLayout()
        total_holder.setLayout(total_holder_layout)
        total_label = QLabel('Total')
        total_label.setFont(self.font_normal)
        total_holder_layout.addWidget(total_label)
        total_input = QLineEdit('10,100')
        total_input.setEnabled(False)
        total_input.setFont(self.font_normal)
        total_holder_layout.addWidget(total_input)
        right_section_layout.addWidget(total_holder)

        button_holder = QWidget()
        button_holder.setMaximumWidth(500)
        button_holder.setMaximumHeight(80)
        button_holder_layout = QHBoxLayout()
        button_holder.setLayout(button_holder_layout)
        button_save = QPushButton('Add to Cart')
        button_save.setFixedHeight(30)
        button_save.setFont(self.font_normal)
        button_holder_layout.addWidget(button_save)
        button_clear = QPushButton('Clear')
        button_clear.setFixedHeight(30)
        button_clear.setFont(self.font_normal)
        button_holder_layout.addWidget(button_clear)
        right_section_layout.addWidget(button_holder)
